<?php

return [

    /*
    |--------------------------------------------------------------------------
    | JWT Secret Key
    |--------------------------------------------------------------------------
    |
    | This key is used to sign JWT tokens for WhatsApp Go API authentication.
    |
    | ⚠️ CRITICAL: This MUST match JWT_SECRET in your Go API .env exactly!
    |
    | The same secret is used in both Laravel and Go to ensure tokens
    | generated by Laravel can be validated by the Go API.
    |
    */

    'secret' => env('JWT_SECRET', ''),

    /*
    |--------------------------------------------------------------------------
    | JWT Issuer
    |--------------------------------------------------------------------------
    |
    | The issuer claim identifies the principal that issued the JWT.
    |
    */

    'issuer' => env('JWT_ISSUER', 'WhatsApp Sender Pro'),

    /*
    |--------------------------------------------------------------------------
    | JWT Time To Live (TTL)
    |--------------------------------------------------------------------------
    |
    | Specify the length of time (in seconds) that the token will be valid for.
    |
    | Default: 86400 seconds (24 hours)
    |
    | Common values:
    | - 3600    = 1 hour
    | - 43200   = 12 hours
    | - 86400   = 24 hours (recommended)
    | - 604800  = 7 days
    |
    */

    'ttl' => env('JWT_TTL', 86400),

    /*
    |--------------------------------------------------------------------------
    | JWT Algorithm
    |--------------------------------------------------------------------------
    |
    | Specify the hashing algorithm that will be used to sign the token.
    |
    | Supported: HS256, HS384, HS512, RS256, RS384, RS512
    | Recommended: HS256 (default)
    |
    */

    'algo' => env('JWT_ALGO', 'HS256'),

    /*
    |--------------------------------------------------------------------------
    | JWT Refresh Window
    |--------------------------------------------------------------------------
    |
    | Time before expiration when token can be refreshed (in seconds).
    |
    | If a token is within this window of expiring, it can be refreshed
    | to get a new token with extended expiration.
    |
    | Default: 3600 seconds (1 hour before expiration)
    |
    */

    'refresh_window' => env('JWT_REFRESH_WINDOW', 3600),

    /*
    |--------------------------------------------------------------------------
    | WhatsApp API URL
    |--------------------------------------------------------------------------
    |
    | The base URL of your WhatsApp Go API.
    |
    | Local: http://localhost:8988
    | Production: https://whatsapp-api.yourdomain.com
    |
    */

    'whatsapp_api_url' => env('WHATSAPP_API_URL', 'http://localhost:8988'),

    /*
    |--------------------------------------------------------------------------
    | Token Caching
    |--------------------------------------------------------------------------
    |
    | Enable/disable token caching to reduce JWT generation overhead.
    |
    | When enabled, tokens are cached in session until near expiration.
    | This improves performance by avoiding regenerating tokens on every request.
    |
    */

    'cache_tokens' => env('JWT_CACHE_TOKENS', false),

    /*
    |--------------------------------------------------------------------------
    | Cache Duration
    |--------------------------------------------------------------------------
    |
    | How long (in seconds) before expiration should we refresh cached tokens?
    |
    | Default: 300 seconds (5 minutes before expiration)
    |
    */

    'cache_refresh_buffer' => env('JWT_CACHE_REFRESH_BUFFER', 300),

];
